# Netlify configuration for Next.js 14 App Router
# Docs: https://docs.netlify.com/integrations/frameworks/next-js/overview/

[build]
  command = "npm run build"
  publish = ".next"
  # Optional: only build when app/ or relevant files change
  # ignore = "git diff --quiet HEAD^ HEAD ./"

# Enable the official Next.js runtime on Netlify
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Recommended Node version
[build.environment]
  NODE_VERSION = "18"
